name: life_logger
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  # sdk: ^3.5.3
  # this is for online editing with 'zapp!'
    sdk: ^2.19.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  firebase_core: ^1.10.0
  table_calendar: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
